name: dependency vulnerability scanning

on:
  schedule:
    - cron: '0 0 */2 * *' # runs every 2 days
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: install dependencies
        run: npm install

      - name: audit dependencies
        run: npm audit --production --audit-level=high
